import { Agent, Task, Run, RunEvent, Message, Conversation, UsageRecord, DailyUsage, ModelUsage } from './types';

// --- Agents ---
export const agents: Agent[] = [
  {
    id: 'agent-001',
    name: 'Scout',
    slug: 'scout',
    description: 'Research and competitive intelligence agent. Gathers market data, analyzes competitors, and produces structured reports.',
    system_prompt: 'You are Scout, a research agent specializing in competitive intelligence. You gather data from public sources, analyze market trends, and produce clear, structured reports. Be thorough but concise.',
    specialization: 'Research & Intel',
    default_model: 'gpt-4o-mini',
    escalation_model: 'claude-3.5-sonnet',
    max_budget_per_run: 0.50,
    allowed_tools: ['web_search', 'scrape_url', 'summarize', 'write_report'],
    is_active: true,
    avatar_color: '#3b82f6',
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-03-22T14:30:00Z',
    total_runs: 247,
    avg_cost_per_run: 0.032,
    recent_runs: 12,
    status: 'busy',
  },
  {
    id: 'agent-002',
    name: 'Coder',
    slug: 'coder',
    description: 'Code generation and review agent. Writes, refactors, and reviews code across multiple languages.',
    system_prompt: 'You are Coder, a senior software engineer agent. You write clean, well-tested code. You follow best practices and explain your decisions briefly. You prefer simplicity over cleverness.',
    specialization: 'Engineering',
    default_model: 'claude-3.5-sonnet',
    escalation_model: 'claude-3-opus',
    max_budget_per_run: 2.00,
    allowed_tools: ['read_file', 'write_file', 'run_tests', 'lint', 'search_code'],
    is_active: true,
    avatar_color: '#8b5cf6',
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-03-23T08:15:00Z',
    total_runs: 189,
    avg_cost_per_run: 0.145,
    recent_runs: 8,
    status: 'busy',
  },
  {
    id: 'agent-003',
    name: 'Writer',
    slug: 'writer',
    description: 'Content creation agent. Drafts blog posts, marketing copy, documentation, and communications.',
    system_prompt: 'You are Writer, a content creation agent. You write clear, engaging prose. You adapt tone to context — technical docs should be precise, marketing copy should be compelling, communications should be warm and professional.',
    specialization: 'Content',
    default_model: 'gpt-4o-mini',
    escalation_model: 'gpt-4o',
    max_budget_per_run: 0.30,
    allowed_tools: ['web_search', 'write_document', 'tone_check'],
    is_active: true,
    avatar_color: '#10b981',
    created_at: '2026-02-20T09:00:00Z',
    updated_at: '2026-03-22T16:00:00Z',
    total_runs: 312,
    avg_cost_per_run: 0.018,
    recent_runs: 15,
    status: 'active',
  },
  {
    id: 'agent-004',
    name: 'Analyst',
    slug: 'analyst',
    description: 'Data analysis and insights agent. Processes datasets, runs queries, and generates analytical summaries.',
    system_prompt: 'You are Analyst, a data analysis agent. You process structured data, identify patterns, and produce clear analytical summaries with actionable insights. Show your work when relevant.',
    specialization: 'Analytics',
    default_model: 'gpt-4o',
    escalation_model: 'claude-3-opus',
    max_budget_per_run: 1.00,
    allowed_tools: ['query_database', 'process_csv', 'chart_data', 'summarize'],
    is_active: true,
    avatar_color: '#f59e0b',
    created_at: '2026-03-01T11:00:00Z',
    updated_at: '2026-03-23T07:45:00Z',
    total_runs: 86,
    avg_cost_per_run: 0.089,
    recent_runs: 5,
    status: 'active',
  },
  {
    id: 'agent-005',
    name: 'Ops',
    slug: 'ops',
    description: 'DevOps and infrastructure agent. Manages deployments, monitors services, and handles incident response.',
    system_prompt: 'You are Ops, a DevOps agent. You handle deployments, monitor infrastructure, and respond to incidents. Prioritize reliability and clear communication. Always explain what you changed and why.',
    specialization: 'DevOps',
    default_model: 'claude-3.5-sonnet',
    escalation_model: 'claude-3-opus',
    max_budget_per_run: 1.50,
    allowed_tools: ['deploy', 'check_status', 'rollback', 'alert', 'run_command'],
    is_active: false,
    avatar_color: '#ef4444',
    created_at: '2026-03-05T14:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
    total_runs: 42,
    avg_cost_per_run: 0.210,
    recent_runs: 0,
    status: 'inactive',
  },
  {
    id: 'agent-006',
    name: 'Planner',
    slug: 'planner',
    description: 'Project planning and task decomposition agent. Breaks down complex objectives into actionable steps.',
    system_prompt: 'You are Planner, a project management agent. You take high-level objectives and break them into clear, actionable tasks with priorities and dependencies. Be structured and practical.',
    specialization: 'Planning',
    default_model: 'gpt-4o-mini',
    escalation_model: 'claude-3.5-sonnet',
    max_budget_per_run: 0.25,
    allowed_tools: ['create_task', 'assign_agent', 'set_priority', 'summarize'],
    is_active: true,
    avatar_color: '#06b6d4',
    created_at: '2026-03-10T08:00:00Z',
    updated_at: '2026-03-23T09:00:00Z',
    total_runs: 64,
    avg_cost_per_run: 0.015,
    recent_runs: 4,
    status: 'active',
  },
];

// --- Tasks ---
export const tasks: Task[] = [
  {
    id: 'task-001',
    title: 'Research competitor pricing for Q2',
    description: 'Analyze pricing pages and plans of top 5 competitors. Produce comparison matrix.',
    priority: 'high',
    status: 'running',
    assigned_agent_id: 'agent-001',
    created_by: 'user',
    created_at: '2026-03-23T08:00:00Z',
    updated_at: '2026-03-23T08:05:00Z',
  },
  {
    id: 'task-002',
    title: 'Refactor auth middleware',
    description: 'Clean up the authentication middleware. Extract token validation into separate module.',
    priority: 'medium',
    status: 'running',
    assigned_agent_id: 'agent-002',
    created_by: 'user',
    created_at: '2026-03-23T07:30:00Z',
    updated_at: '2026-03-23T07:35:00Z',
  },
  {
    id: 'task-003',
    title: 'Write changelog for v2.4 release',
    description: 'Draft a user-facing changelog based on the merged PRs since v2.3.',
    priority: 'medium',
    status: 'completed',
    assigned_agent_id: 'agent-003',
    created_by: 'user',
    created_at: '2026-03-22T14:00:00Z',
    updated_at: '2026-03-22T14:45:00Z',
  },
  {
    id: 'task-004',
    title: 'Analyze user retention cohorts',
    description: 'Run cohort analysis on last 90 days of user data. Identify drop-off points.',
    priority: 'high',
    status: 'needs_approval',
    assigned_agent_id: 'agent-004',
    created_by: 'user',
    created_at: '2026-03-23T06:00:00Z',
    updated_at: '2026-03-23T09:30:00Z',
  },
  {
    id: 'task-005',
    title: 'Draft investor update email',
    description: 'Write monthly investor update covering metrics, milestones, and upcoming plans.',
    priority: 'high',
    status: 'queued',
    assigned_agent_id: 'agent-003',
    created_by: 'user',
    created_at: '2026-03-23T09:00:00Z',
    updated_at: '2026-03-23T09:00:00Z',
  },
  {
    id: 'task-006',
    title: 'Fix pagination bug in /api/products',
    description: 'Offset-based pagination returns duplicates when items are added during traversal.',
    priority: 'critical',
    status: 'failed',
    assigned_agent_id: 'agent-002',
    created_by: 'user',
    created_at: '2026-03-22T16:00:00Z',
    updated_at: '2026-03-22T16:30:00Z',
  },
  {
    id: 'task-007',
    title: 'Plan Q2 product roadmap breakdown',
    description: 'Take the Q2 strategy doc and decompose it into epics and tasks.',
    priority: 'medium',
    status: 'running',
    assigned_agent_id: 'agent-006',
    created_by: 'user',
    created_at: '2026-03-23T09:15:00Z',
    updated_at: '2026-03-23T09:20:00Z',
  },
  {
    id: 'task-008',
    title: 'Generate SEO blog post on AI agents',
    description: 'Write a 1500-word SEO-optimized blog post about AI agent orchestration.',
    priority: 'low',
    status: 'queued',
    assigned_agent_id: 'agent-003',
    created_by: 'user',
    created_at: '2026-03-23T09:30:00Z',
    updated_at: '2026-03-23T09:30:00Z',
  },
  {
    id: 'task-009',
    title: 'Review PR #482 - payment flow',
    description: 'Review the payment flow refactor PR for correctness and security.',
    priority: 'high',
    status: 'stalled',
    assigned_agent_id: 'agent-002',
    created_by: 'user',
    created_at: '2026-03-22T11:00:00Z',
    updated_at: '2026-03-23T02:00:00Z',
  },
];

// --- Runs ---
const now = new Date('2026-03-23T10:00:00Z');
function hoursAgo(h: number): string {
  return new Date(now.getTime() - h * 3600000).toISOString();
}
function minutesAgo(m: number): string {
  return new Date(now.getTime() - m * 60000).toISOString();
}

export const runs: Run[] = [
  {
    id: 'run-001',
    task_id: 'task-001',
    agent_id: 'agent-001',
    status: 'running',
    actual_model_used: 'gpt-4o-mini',
    started_at: minutesAgo(45),
    ended_at: null,
    input_tokens: 12400,
    output_tokens: 3200,
    estimated_cost: 0.0038,
    retry_count: 0,
    parent_run_id: null,
    agent_name: 'Scout',
    task_title: 'Research competitor pricing for Q2',
  },
  {
    id: 'run-002',
    task_id: 'task-002',
    agent_id: 'agent-002',
    status: 'running',
    actual_model_used: 'claude-3.5-sonnet',
    started_at: minutesAgo(30),
    ended_at: null,
    input_tokens: 45000,
    output_tokens: 18000,
    estimated_cost: 0.405,
    retry_count: 0,
    parent_run_id: null,
    agent_name: 'Coder',
    task_title: 'Refactor auth middleware',
  },
  {
    id: 'run-003',
    task_id: 'task-003',
    agent_id: 'agent-003',
    status: 'completed',
    actual_model_used: 'gpt-4o-mini',
    started_at: hoursAgo(20),
    ended_at: hoursAgo(19.5),
    input_tokens: 8200,
    output_tokens: 2100,
    estimated_cost: 0.0025,
    retry_count: 0,
    parent_run_id: null,
    agent_name: 'Writer',
    task_title: 'Write changelog for v2.4 release',
  },
  {
    id: 'run-004',
    task_id: 'task-004',
    agent_id: 'agent-004',
    status: 'needs_approval',
    actual_model_used: 'gpt-4o',
    started_at: hoursAgo(4),
    ended_at: minutesAgo(30),
    input_tokens: 52000,
    output_tokens: 15000,
    estimated_cost: 0.280,
    retry_count: 0,
    parent_run_id: null,
    agent_name: 'Analyst',
    task_title: 'Analyze user retention cohorts',
  },
  {
    id: 'run-005',
    task_id: 'task-006',
    agent_id: 'agent-002',
    status: 'failed',
    actual_model_used: 'claude-3.5-sonnet',
    started_at: hoursAgo(18),
    ended_at: hoursAgo(17.5),
    input_tokens: 32000,
    output_tokens: 8500,
    estimated_cost: 0.224,
    retry_count: 2,
    parent_run_id: null,
    agent_name: 'Coder',
    task_title: 'Fix pagination bug in /api/products',
  },
  {
    id: 'run-006',
    task_id: 'task-007',
    agent_id: 'agent-006',
    status: 'running',
    actual_model_used: 'gpt-4o-mini',
    started_at: minutesAgo(20),
    ended_at: null,
    input_tokens: 6800,
    output_tokens: 4200,
    estimated_cost: 0.0035,
    retry_count: 0,
    parent_run_id: null,
    agent_name: 'Planner',
    task_title: 'Plan Q2 product roadmap breakdown',
  },
  {
    id: 'run-007',
    task_id: 'task-009',
    agent_id: 'agent-002',
    status: 'stalled',
    actual_model_used: 'claude-3.5-sonnet',
    started_at: hoursAgo(23),
    ended_at: null,
    input_tokens: 28000,
    output_tokens: 0,
    estimated_cost: 0.084,
    retry_count: 0,
    parent_run_id: null,
    agent_name: 'Coder',
    task_title: 'Review PR #482 - payment flow',
  },
  {
    id: 'run-008',
    task_id: 'task-001',
    agent_id: 'agent-001',
    status: 'completed',
    actual_model_used: 'gpt-4o-mini',
    started_at: hoursAgo(3),
    ended_at: hoursAgo(2.5),
    input_tokens: 15000,
    output_tokens: 5200,
    estimated_cost: 0.0054,
    retry_count: 0,
    parent_run_id: 'run-001',
    agent_name: 'Scout',
    task_title: 'Research competitor pricing for Q2 — sub-task: pricing page scrape',
  },
];

// --- Run Events (for run-002 as detailed example) ---
export const runEvents: RunEvent[] = [
  {
    id: 'evt-001',
    run_id: 'run-002',
    timestamp: minutesAgo(30),
    event_type: 'started',
    status: 'running',
    summary: 'Run started. Agent Coder assigned.',
    metadata: { model: 'claude-3.5-sonnet' },
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    tool_name: null,
  },
  {
    id: 'evt-002',
    run_id: 'run-002',
    timestamp: minutesAgo(29),
    event_type: 'model_called',
    status: 'running',
    summary: 'Initial analysis of auth middleware structure.',
    metadata: {},
    input_tokens: 8200,
    output_tokens: 1500,
    estimated_cost: 0.047,
    tool_name: null,
  },
  {
    id: 'evt-003',
    run_id: 'run-002',
    timestamp: minutesAgo(27),
    event_type: 'tool_call',
    status: 'running',
    summary: 'Read file: server/middleware/auth.ts',
    metadata: { path: 'server/middleware/auth.ts', lines: 142 },
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    tool_name: 'read_file',
  },
  {
    id: 'evt-004',
    run_id: 'run-002',
    timestamp: minutesAgo(26),
    event_type: 'tool_result',
    status: 'running',
    summary: 'File read successfully. 142 lines.',
    metadata: {},
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    tool_name: 'read_file',
  },
  {
    id: 'evt-005',
    run_id: 'run-002',
    timestamp: minutesAgo(24),
    event_type: 'model_called',
    status: 'running',
    summary: 'Planning refactor: extract token validation into server/auth/validate-token.ts',
    metadata: {},
    input_tokens: 12000,
    output_tokens: 4500,
    estimated_cost: 0.104,
    tool_name: null,
  },
  {
    id: 'evt-006',
    run_id: 'run-002',
    timestamp: minutesAgo(20),
    event_type: 'tool_call',
    status: 'running',
    summary: 'Write file: server/auth/validate-token.ts',
    metadata: { path: 'server/auth/validate-token.ts', lines: 48 },
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    tool_name: 'write_file',
  },
  {
    id: 'evt-007',
    run_id: 'run-002',
    timestamp: minutesAgo(18),
    event_type: 'tool_call',
    status: 'running',
    summary: 'Write file: server/middleware/auth.ts (updated)',
    metadata: { path: 'server/middleware/auth.ts', lines: 89 },
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    tool_name: 'write_file',
  },
  {
    id: 'evt-008',
    run_id: 'run-002',
    timestamp: minutesAgo(15),
    event_type: 'tool_call',
    status: 'running',
    summary: 'Running test suite: auth tests',
    metadata: { command: 'npm run test -- --filter auth' },
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    tool_name: 'run_tests',
  },
  {
    id: 'evt-009',
    run_id: 'run-002',
    timestamp: minutesAgo(12),
    event_type: 'tool_result',
    status: 'running',
    summary: 'Tests passed: 14/14',
    metadata: { passed: 14, failed: 0, skipped: 0 },
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    tool_name: 'run_tests',
  },
  {
    id: 'evt-010',
    run_id: 'run-002',
    timestamp: minutesAgo(10),
    event_type: 'model_called',
    status: 'running',
    summary: 'Writing summary of changes and creating PR description.',
    metadata: {},
    input_tokens: 24800,
    output_tokens: 12000,
    estimated_cost: 0.254,
    tool_name: null,
  },
];

// --- Conversations ---
export const conversations: Conversation[] = [
  {
    id: 'conv-001',
    title: 'Competitor pricing research',
    agent_id: 'agent-001',
    task_id: 'task-001',
    status: 'active',
    last_message_at: minutesAgo(2),
    message_count: 8,
    total_cost: 0.0038,
  },
  {
    id: 'conv-002',
    title: 'Auth middleware refactor',
    agent_id: 'agent-002',
    task_id: 'task-002',
    status: 'active',
    last_message_at: minutesAgo(10),
    message_count: 12,
    total_cost: 0.405,
  },
  {
    id: 'conv-003',
    title: 'v2.4 changelog draft',
    agent_id: 'agent-003',
    task_id: 'task-003',
    status: 'completed',
    last_message_at: hoursAgo(19.5),
    message_count: 6,
    total_cost: 0.0025,
  },
  {
    id: 'conv-004',
    title: 'Retention cohort analysis',
    agent_id: 'agent-004',
    task_id: 'task-004',
    status: 'active',
    last_message_at: minutesAgo(30),
    message_count: 10,
    total_cost: 0.280,
  },
  {
    id: 'conv-005',
    title: 'Q2 roadmap planning',
    agent_id: 'agent-006',
    task_id: 'task-007',
    status: 'active',
    last_message_at: minutesAgo(5),
    message_count: 4,
    total_cost: 0.0035,
  },
];

// --- Messages (for conv-002) ---
export const messages: Message[] = [
  {
    id: 'msg-001',
    conversation_id: 'conv-002',
    role: 'user',
    content: 'Refactor the auth middleware in server/middleware/auth.ts. Extract the token validation logic into its own module so we can reuse it in WebSocket auth.',
    agent_id: null,
    model: null,
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    created_at: minutesAgo(30),
  },
  {
    id: 'msg-002',
    conversation_id: 'conv-002',
    role: 'assistant',
    content: "I'll analyze the current auth middleware and extract the token validation logic. Let me start by reading the existing file.",
    agent_id: 'agent-002',
    model: 'claude-3.5-sonnet',
    input_tokens: 8200,
    output_tokens: 1500,
    estimated_cost: 0.047,
    tool_calls: [
      {
        id: 'tc-001',
        name: 'read_file',
        input: '{"path": "server/middleware/auth.ts"}',
        output: '// File contents: 142 lines of auth middleware...',
        duration_ms: 120,
      },
    ],
    created_at: minutesAgo(29),
  },
  {
    id: 'msg-003',
    conversation_id: 'conv-002',
    role: 'assistant',
    content: "I've read the auth middleware. Here's my plan:\n\n1. Extract `validateToken()` and `decodePayload()` into `server/auth/validate-token.ts`\n2. Update the middleware to import from the new module\n3. Export types for the token payload\n4. Run existing tests to verify nothing breaks\n\nLet me proceed with the extraction.",
    agent_id: 'agent-002',
    model: 'claude-3.5-sonnet',
    input_tokens: 12000,
    output_tokens: 4500,
    estimated_cost: 0.104,
    created_at: minutesAgo(27),
  },
  {
    id: 'msg-004',
    conversation_id: 'conv-002',
    role: 'assistant',
    content: "I've created the new module and updated the middleware. Here's what changed:\n\n**New file: `server/auth/validate-token.ts`** (48 lines)\n- `validateToken(token: string): TokenPayload`\n- `decodePayload(token: string): JwtPayload`  \n- Exported `TokenPayload` type\n\n**Updated: `server/middleware/auth.ts`** (89 lines, was 142)\n- Now imports from `./auth/validate-token`\n- Removed inline validation logic\n- Cleaner error handling\n\nRunning tests now...",
    agent_id: 'agent-002',
    model: 'claude-3.5-sonnet',
    input_tokens: 18000,
    output_tokens: 8000,
    estimated_cost: 0.174,
    tool_calls: [
      {
        id: 'tc-002',
        name: 'write_file',
        input: '{"path": "server/auth/validate-token.ts"}',
        output: 'File written successfully.',
        duration_ms: 45,
      },
      {
        id: 'tc-003',
        name: 'write_file',
        input: '{"path": "server/middleware/auth.ts"}',
        output: 'File written successfully.',
        duration_ms: 38,
      },
      {
        id: 'tc-004',
        name: 'run_tests',
        input: '{"command": "npm run test -- --filter auth"}',
        output: 'Tests passed: 14/14\nAll auth tests passing.',
        duration_ms: 3200,
      },
    ],
    created_at: minutesAgo(15),
  },
  {
    id: 'msg-005',
    conversation_id: 'conv-002',
    role: 'assistant',
    content: "All 14 auth tests pass. The refactor is clean — reduced the middleware from 142 to 89 lines, and the new `validate-token.ts` module is 48 lines. The token validation logic is now reusable for your WebSocket auth.\n\nWould you like me to create a PR, or should I also update the WebSocket handler to use the new module?",
    agent_id: 'agent-002',
    model: 'claude-3.5-sonnet',
    input_tokens: 24800,
    output_tokens: 12000,
    estimated_cost: 0.254,
    created_at: minutesAgo(10),
  },
  {
    id: 'msg-006',
    conversation_id: 'conv-002',
    role: 'user',
    content: 'Great work. Go ahead and update the WebSocket handler too, then create the PR.',
    agent_id: null,
    model: null,
    input_tokens: null,
    output_tokens: null,
    estimated_cost: null,
    created_at: minutesAgo(8),
  },
];

// --- Usage Data ---
export const dailyUsage: DailyUsage[] = [
  { date: '2026-03-17', input_tokens: 820000, output_tokens: 245000, estimated_cost: 4.82, runs: 34 },
  { date: '2026-03-18', input_tokens: 1050000, output_tokens: 380000, estimated_cost: 6.94, runs: 42 },
  { date: '2026-03-19', input_tokens: 680000, output_tokens: 195000, estimated_cost: 3.45, runs: 28 },
  { date: '2026-03-20', input_tokens: 1240000, output_tokens: 420000, estimated_cost: 8.12, runs: 51 },
  { date: '2026-03-21', input_tokens: 950000, output_tokens: 310000, estimated_cost: 5.67, runs: 38 },
  { date: '2026-03-22', input_tokens: 1180000, output_tokens: 390000, estimated_cost: 7.45, runs: 46 },
  { date: '2026-03-23', input_tokens: 456000, output_tokens: 142000, estimated_cost: 3.21, runs: 18 },
];

export const modelUsage: ModelUsage[] = [
  { model: 'gpt-4o-mini', tier: 'cheap', input_tokens: 2800000, output_tokens: 920000, estimated_cost: 0.97, percentage: 45 },
  { model: 'claude-3.5-sonnet', tier: 'mid', input_tokens: 2100000, output_tokens: 680000, estimated_cost: 16.50, percentage: 30 },
  { model: 'gpt-4o', tier: 'mid', input_tokens: 980000, output_tokens: 310000, estimated_cost: 5.55, percentage: 15 },
  { model: 'claude-3-opus', tier: 'premium', input_tokens: 320000, output_tokens: 95000, estimated_cost: 11.93, percentage: 7 },
  { model: 'gpt-4-turbo', tier: 'premium', input_tokens: 180000, output_tokens: 77000, estimated_cost: 4.11, percentage: 3 },
];

// --- Aggregate helpers ---
export function getTodayUsage() {
  const today = dailyUsage[dailyUsage.length - 1];
  return {
    tokens: today.input_tokens + today.output_tokens,
    cost: today.estimated_cost,
    runs: today.runs,
  };
}

export function getActiveRuns() {
  return runs.filter(r => r.status === 'running');
}

export function getQueuedTasks() {
  return tasks.filter(t => t.status === 'queued');
}

export function getFailedRuns() {
  return runs.filter(r => r.status === 'failed');
}

export function getStalledRuns() {
  return runs.filter(r => r.status === 'stalled');
}

export function getNeedsApproval() {
  return tasks.filter(t => t.status === 'needs_approval');
}

export function getOnlineAgents() {
  return agents.filter(a => a.is_active);
}

export function getRecentActivity() {
  return [
    { id: 'act-1', text: 'Scout started researching competitor pricing', time: minutesAgo(45), type: 'started' as const },
    { id: 'act-2', text: 'Coder began auth middleware refactor', time: minutesAgo(30), type: 'started' as const },
    { id: 'act-3', text: 'Planner started Q2 roadmap decomposition', time: minutesAgo(20), type: 'started' as const },
    { id: 'act-4', text: 'Analyst completed retention cohort analysis — awaiting approval', time: minutesAgo(30), type: 'needs_approval' as const },
    { id: 'act-5', text: 'Coder failed on pagination bug fix — 2 retries exhausted', time: hoursAgo(17.5), type: 'failed' as const },
    { id: 'act-6', text: 'Writer completed v2.4 changelog draft', time: hoursAgo(19.5), type: 'completed' as const },
    { id: 'act-7', text: 'Coder stalled on PR #482 review — waiting for API access', time: hoursAgo(8), type: 'stalled' as const },
    { id: 'act-8', text: 'Scout completed sub-task: pricing page scrape', time: hoursAgo(2.5), type: 'completed' as const },
  ];
}
