import { store } from './store'
import { WORKFLOW_CHAINS } from './workflow-chains'

/**
 * Workflow orchestrator — checks active workflow instances after each sync
 * and auto-advances to the next step when the current step's run completes.
 *
 * This runs server-side in the sync cycle. It does not launch agents —
 * it creates a queued task for the next role in the chain, which the
 * dashboard surfaces for the user to deploy (or auto-deploy in the future).
 *
 * Call checkWorkflows() after each sync cycle to process pending handoffs.
 */

export function checkWorkflows(): void {
  const instances = store.getWorkflowInstances()

  for (const instance of instances) {
    if (instance.status !== 'running' && instance.status !== 'waiting') continue

    const chain = WORKFLOW_CHAINS.find((c) => c.id === instance.chain_id)
    if (!chain) continue

    const currentStep = instance.current_step
    if (currentStep >= chain.steps.length) {
      // Chain is done — mark completed
      instance.status = 'completed'
      instance.updated_at = new Date().toISOString()
      store.upsertWorkflowInstance(instance)
      continue
    }

    // Check if current step has a run assigned
    const currentRunId = instance.step_run_ids[currentStep]

    if (currentRunId) {
      // Check if the run completed
      const run = store.getRuns().find((r) => r.id === currentRunId)

      if (run?.status === 'completed') {
        // Advance to next step
        const nextStep = currentStep + 1

        if (nextStep >= chain.steps.length) {
          // Chain complete
          instance.current_step = nextStep
          instance.status = 'completed'
          instance.updated_at = new Date().toISOString()
          store.upsertWorkflowInstance(instance)
          console.log(`[workflow] Chain "${chain.name}" completed for project ${instance.project_id}`)
        } else {
          // Create a queued task for the next step
          const nextStepDef = chain.steps[nextStep]
          const assignment = store.getRoleAssignments(instance.project_id)
            .find((a) => a.role === nextStepDef.role)

          const taskId = `task-wf-${instance.id}-step-${nextStep}`

          // Only create the task if it doesn't already exist
          if (!store.getTask(taskId)) {
            store.upsertTask({
              id: taskId,
              title: `[${chain.name}] Step ${nextStep + 1}: ${nextStepDef.action}`,
              description: `Auto-generated by workflow "${chain.name}". Previous step output available from run ${currentRunId}.`,
              priority: 'medium',
              status: 'queued',
              assigned_agent_id: assignment?.agent_id ?? null,
              created_by: 'workflow-orchestrator',
              project_id: instance.project_id,
              created_at: new Date().toISOString(),
              updated_at: new Date().toISOString(),
            })

            console.log(
              `[workflow] Advanced "${chain.name}" to step ${nextStep + 1} (${nextStepDef.role}: ${nextStepDef.action})`
            )
          }

          instance.current_step = nextStep
          instance.status = 'waiting' // waiting for user to deploy or auto-deploy
          instance.updated_at = new Date().toISOString()
          store.upsertWorkflowInstance(instance)
        }
      } else if (run?.status === 'failed') {
        // Mark workflow as failed
        instance.status = 'failed'
        instance.updated_at = new Date().toISOString()
        store.upsertWorkflowInstance(instance)
        console.log(`[workflow] Chain "${chain.name}" failed at step ${currentStep + 1}`)
      }
    }
    // If no run assigned yet, the workflow is waiting for the user to launch
  }
}
